### ISSUE TITLE
Cumulated rainfall - Visualization issue

### ISSUE THREAD

**Issue by paolamazzoglio** [ITHACA-org/erds-web#27] opened 2019-06-10 08:32 UTC
The cumulated rainfall shown through the WMS has a "hole" (i.e, no data) when the rainfall amount is greater than 1500 mm. Raster file, instead, are correct. It is advisable to increase the upper limits (using, for example, 3000 mm).

![image](https://user-images.githubusercontent.com/44401784/59182428-0947b780-8b6a-11e9-9ca2-b7ea11df726c.png)

CODE: https://github.com/ITHACA-org/erds-web/blob/master/utils/erds_precip.sld

**Comment by ppasq** [comment] 2019-06-12 07:46
I have increased the upper quantity. @paolamazzoglio pls close this issue if the problem is solved. Thx.

**Closed as completed** 2019-06-12 07:49 UTC
